---
- name: install dotdeb key
  apt_key: url=http://www.dotdeb.org/dotdeb.gpg state=present
  tags: dotdeb
  when: ansible_distribution == "Debian"

- name: add dotdeb repository
  apt_repository: repo='{{ item }}' state=present
  register: dotdeb_installed
  with_items:
    - "deb http://packages.dotdeb.org {{ ansible_distribution_release }} all"
    - "deb-src http://packages.dotdeb.org {{ ansible_distribution_release }} all"
  notify: update apt cache
  tags: dotdeb
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version >= "6"
    - ansible_distribution_major_version <= "8"
